when@dev: &web_profiler
  web_profiler:
    toolbar: true
    intercept_redirects: false

  framework:
    profiler: { only_exceptions: false }

when@staging: *web_profiler
when@ipad_dev: *web_profiler
when@ipad_staging: *web_profiler
