name: mbuddy
services:
  php:
    build:
      context: ../
      dockerfile: docker/php/Dockerfile
    volumes:
      - ../:/usr/src/MBuddy
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    working_dir: /usr/src/MBuddy
    ports:
      - 8383:8383
      - 8484:8484
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      DEV_HOST: 127.0.0.1

  webdriver:
    build:
      dockerfile: webdriver/Dockerfile
    ports:
      - 4444:4444

  node:
    build:
      context: node/
      dockerfile: Dockerfile
    working_dir: /usr/src/
    volumes:
      - ../:/usr/src/MBuddy
