<?php
return [
    [1, "I Wish"],
    [3, "Hold On To Me"],
    [22, "Never Too Much"],
    [17, "How Far We've Come"],
    [2, "Too Young To Die"],
    [11, "Staying Alive"],
    [15, "1975"],
    [20, "Street Life"],
    [16, "Get Into My Groove"],

    [10, "Love Foolosophy"],
    [8, "Roof Garden"],
    [13, "Love Got In The Way"],
    [9, "Midnight D'Influence"],
    [5, "Mornin'"],
    [14, "Shade Of Blue"],
    [18, "Golden"],
    [21, "I Got A Work To Do"],
    [4, "Sledgehammer"],
    [12, "I Feel It Coming"],
    [19, "Deep Water"],
    [6, "Kiss"],
    [7, "Good Times"],
];
