# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
  env(DEV_HOST): 192.168.1.22
  dev_host: '%env(DEV_HOST)%'
  ipad_host: 192.168.1.161
  mbuddy_base_path: /MBuddy

services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  # makes classes in src/ available to be used as services
  # this creates a service per class whose id is the fully-qualified class name
  Bveing\MBuddy\:
    resource: '../src/'
    exclude:
      - '../src/App/Kernel.php'

  # add more service definitions when explicit configuration is needed
  # please note that last definitions always *replace* previous ones


  Bveing\MBuddy\App\Server:
    public: true
    arguments:
      $port: 8383

  Symfony\Bridge\PsrHttpMessage\Factory\HttpFoundationFactory: ~
  React\Http\Middleware\RequestBodyParserMiddleware: ~
  Amp\Http\Server\RequestHandler\CallableRequestHandler: ~

  Bveing\MBuddy\Infrastructure\App\Core\Preset\FileRepository:
    arguments:
      $filepath: '%kernel.project_dir%/var/presets.json'

  Bveing\MBuddy\App\ScoreStorage:
    arguments:
      $basePath: '%kernel.project_dir%/var/scores'

  mbuddy.motif.master.repository:
    stack:
      - Bveing\MBuddy\Motif\Master\Repository\Decorator\Delay:
          $delayMs: 5000
      - Bveing\MBuddy\Motif\Master\Repository\InMemory: ~
  Bveing\MBuddy\Motif\Master\Repository: '@mbuddy.motif.master.repository'

  mbuddy.motif.master.registry:
    stack:
      - Bveing\MBuddy\Infrastructure\App\Motif\Master\Registry\InMemoryCache:
      - Bveing\MBuddy\Infrastructure\App\Motif\Master\Registry\FileCache:
          $cacheDir: '%kernel.project_dir%/var/motif/'
      - Bveing\MBuddy\Infrastructure\App\Motif\Master\Registry\Motif: ~
  Bveing\MBuddy\App\Motif\Master\Registry: '@mbuddy.motif.master.registry'

when@ipad_dev:
  services:
    logger:
      class: Bveing\MBuddy\Infrastructure\UdpLogger
      factory: ['Bveing\MBuddy\Infrastructure\UdpLogger', 'create']
      arguments:
        - '%dev_host%:8484'
